services:
  database:
    image: mariadb:11.8.5-ubi9
    container_name: f1-quality-gate-db
    restart: unless-stopped
    environment:
      MARIADB_ROOT_PASSWORD: root
      MARIADB_DATABASE: f1_quality_gate
      MARIADB_USER: f1_user
      MARIADB_PASSWORD: f1_password
    ports:
      - "3307:3306"
    volumes:
      - mariadb_data:/var/lib/mysql

volumes:
  mariadb_data: