services:
  database:
    image: mariadb:11.8.5-ubi9
    container_name: f1-quality-gate-db
    restart: unless-stopped
    environment:
      MARIADB_ROOT_PASSWORD: root
      MARIADB_DATABASE: f1_quality_gate
      MARIADB_USER: f1_user
      MARIADB_PASSWORD: f1_password
    ports:
      - "3307:3306"
    volumes:
      - mariadb_data:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin:5.2.3
    container_name: f1-quality-gate-phpmyadmin
    ports:
      - "8082:80"
    environment:
      - PMA_ARBITRARY=1
      - PMA_HOST=database
      - PMA_USER=f1_user
      - PMA_PASSWORD=f1_password
    depends_on:
      - database
    restart: unless-stopped

volumes:
  mariadb_data: