sonar.projectKey=f1-quality-gate
sonar.projectName="F1 Quality Gate"
sonar.projectVersion=1.0.0

sonar.sources=src/main/java
sonar.tests=src/test/java

sonar.java.binaries=target/classes
sonar.coverage.jacoco.xmlReportPaths=target/site/jacoco/jacoco.xml

sonar.sourceEncoding=UTF-8

sonar.coverage.exclusions=**/model/entity/**,**/*Application.java